spring:
  datasource:
    url: jdbc:h2:file:~/data/tictactoe
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console.enabled: true

